PHP Bench

diff --git a/context/run b/context/run
--- a/context/run
+++ b/context/run
@@ -6,6 +6,10 @@ if [[ ${1-} =~ ^[0-9]+$ ]]; then
 fi
 cd /src/php-8.2.0
 printf "COMMAND: make -j%s &>/dev/null\n" "${NCPU}"
+if ! make clean &>/dev/null; then
+  printf -- "CLEANUP FAILED\n"
+  exit 1
+fi
 if /usr/bin/time -o /dev/stdin --quiet -f 'RESULT: %E / %e (%S/%U)' make -j${NCPU} &>/dev/null; then
   printf -- "OK\n"
 else
